import { createApi, fetchBaseQuery } from "@reduxjs/toolkit/query/react";

// Define your base URL
const baseUrl = "https://back.biopluskw.com/api/v1";

// Create the API slice using RTK Query
export const aboutApi = createApi({
  reducerPath: "aboutApi",
  baseQuery: fetchBaseQuery({
    baseUrl,
    prepareHeaders: (headers) => {
      // Get the token from localStorage (or Redux state)
      const token = localStorage.getItem("token");

      // If a token exists, add it to the headers
      if (token) {
        headers.set("Authorization", `Bearer ${token}`);
      }

      return headers;
    },
  }),

  endpoints: (builder) => ({

    getAbout: builder.query({
      query: (id) => `/admin/about-us`,
    }),
    addAbout: builder.mutation({
      query: (data) => ({
        url: "/admin/about-us",
        method: "POST",
        body: data,
      }),
    }),
  }),
});

// Export hooks generated by the API service
export const {
  useGetAboutQuery,
  useAddAboutMutation,
} = aboutApi;
