import { createApi, fetchBaseQuery } from "@reduxjs/toolkit/query/react";

// Define your base URL
const baseUrl = "https://back.biopluskw.com/api/v1";

// Create the API slice using RTK Query
export const adsApi = createApi({
  reducerPath: "adsApi",
  baseQuery: fetchBaseQuery({
    baseUrl,
    prepareHeaders: (headers) => {
      // Get the token from localStorage (or Redux state)
      const token = localStorage.getItem("token");

      // If a token exists, add it to the headers
      if (token) {
        headers.set("Authorization", `Bearer ${token}`);
      }

      return headers;
    },
  }),

  endpoints: (builder) => ({
    getAds: builder.query({
      query: (params) => ({
        url: '/admin/ads',
        params: params, // Sends { page: 1, limit: 10 } as query params
      }),
    }),
    
    getAd: builder.query({
      query: (id) => `/admin/ads/${id}`,
    }),
    addAd: builder.mutation({
      query: (Ad) => ({
        url: "/admin/ads",
        method: "POST",
        body: Ad,
      }),
    }),
    updateAd: builder.mutation({
      query: ({ id, Ad }) => ({
        url: `/admin/ads/${id}`,
        method: "PUT",
        body: Ad,
      }),
    }),
    deleteAd: builder.mutation({
      query: (id) => ({
        url: `/admin/ads/${id}`,
        method: "DELETE",
      }),
    }),
  }),
});

// Export hooks generated by the API service
export const {
  useGetAdsQuery,
  useGetAdQuery,
  useAddAdMutation,
  useUpdateAdMutation,
  useDeleteAdMutation,
} = adsApi;

