import { createApi, fetchBaseQuery } from "@reduxjs/toolkit/query/react";

// Define your base URL
const baseUrl = "https://back.biopluskw.com/api/v1";

// Create the API slice using RTK Query
export const appointmentSlice = createApi({
  reducerPath: "appointmentSlice",
  baseQuery: fetchBaseQuery({
    baseUrl,
    prepareHeaders: (headers) => {
      // Get the token from localStorage (or Redux state)
      const token = localStorage.getItem("token");

      // If a token exists, add it to the headers
      if (token) {
        headers.set("Authorization", `Bearer ${token}`);
      }

      return headers;
    },
  }),

  endpoints: (builder) => ({

    getAppointments: builder.query({
      query: (params) => ({
        url: `/shared/dashboard/appointments`,
        params,
      }),
    }),

  }),
});

// Export hooks generated by the API service
export const {
 useGetAppointmentsQuery
} = appointmentSlice;
