import { createApi, fetchBaseQuery } from "@reduxjs/toolkit/query/react";

// Define your base URL
const baseUrl = "https://back.biopluskw.com/api/v1";

// Create the API slice using RTK Query
export const BannerApi = createApi({
  reducerPath: "BannerApi",
  baseQuery: fetchBaseQuery({
    baseUrl,
    prepareHeaders: (headers) => {
      // Get the token from localStorage (or Redux state)
      const token = localStorage.getItem("token");

      // If a token exists, add it to the headers
      if (token) {
        headers.set("Authorization", `Bearer ${token}`);
      }

      return headers;
    },
  }),

  endpoints: (builder) => ({
    getBanners: builder.query({
      query: (params) => ({
        url: '/admin/banners',
        params: params, // Sends { page: 1, limit: 10 } as query params
      }),
    }),
    
    getBanner: builder.query({
      query: (id) => `/admin/banners/${id}`,
    }),
    addBanner: builder.mutation({
      query: (data) => ({
        url: "/admin/banners",
        method: "POST",
        body: data,
      }),
    }),
    updateBanner: builder.mutation({
      query: ({ id, data }) => ({
        url: `/admin/banners/${id}`,
        method: "PUT",
        body: data,
      }),
    }),
    deleteBanner: builder.mutation({
      query: (id) => ({
        url: `/admin/banners/${id}`,
        method: "DELETE",
      }),
    }),
  }),
});

// Export hooks generated by the API service
export const {
  useGetBannersQuery,
  useGetBannerQuery,
  useAddBannerMutation,
  useUpdateBannerMutation,
  useDeleteBannerMutation,
} = BannerApi;

