import { createApi, fetchBaseQuery } from "@reduxjs/toolkit/query/react";

// Define your base URL
const baseUrl = "https://back.biopluskw.com/api/v1";

// Create the API slice using RTK Query
export const specializationApi = createApi({
  reducerPath: "specializationApi",
  baseQuery: fetchBaseQuery({
    baseUrl,
    prepareHeaders: (headers) => {
      // Get the token from localStorage (or Redux state)
      const token = localStorage.getItem("token");

      // If a token exists, add it to the headers
      if (token) {
        headers.set("Authorization", `Bearer ${token}`);
      }

      return headers;
    },
  }),

  endpoints: (builder) => ({
    getSpecializations: builder.query({
      query: (params) => ({
        url: '/admin/doctor-specializations',
        params: params, // Sends { page: 1, limit: 10 } as query params
      }),
    }),
    
    getSpecialization: builder.query({
      query: (id) => `/admin/doctor-specializations/${id}`,
    }),
    addSpecialization: builder.mutation({
      query: (data) => ({
        url: "/admin/doctor-specializations",
        method: "POST",
        body: data,
      }),
    }),
    updateSpecialization: builder.mutation({
      query: ({ id, data }) => ({
        url: `/admin/doctor-specializations/${id}`,
        method: "PUT",
        body: data,
      }),
    }),
    deleteSpecialization: builder.mutation({
      query: (id) => ({
        url: `/admin/doctor-specializations/${id}`,
        method: "DELETE",
      }),
    }),
  }),
});

// Export hooks generated by the API service
export const {
  useGetSpecializationsQuery,
  useGetSpecializationQuery,
  useAddSpecializationMutation,
  useUpdateSpecializationMutation,
  useDeleteSpecializationMutation,
} = specializationApi;

