import { createApi, fetchBaseQuery } from "@reduxjs/toolkit/query/react";

// Define your base URL
const baseUrl = "https://back.biopluskw.com/api/v1";

// Create the API slice using RTK Query
export const homeBannerSlice = createApi({
  reducerPath: "homeBannerApi",
  baseQuery: fetchBaseQuery({
    baseUrl,
    prepareHeaders: (headers) => {
      const token = localStorage.getItem("token");
      if (token) {
        headers.set("Authorization", `Bearer ${token}`);
      }
      return headers;
    },
  }),
  tagTypes: ['Banner'],
  endpoints: (builder) => ({

    // GET banners
    getBanners: builder.query({
      query: (params) => ({
        url: '/admin/home-banners',
        params,
      }),
      providesTags: ['Banner'],
    }),

    // POST create banner
    createBanner: builder.mutation({
      query: (newBannerData) => ({
        url: '/admin/home-banners',
        method: 'POST',
        body: newBannerData,
      }),
      invalidatesTags: ['Banner'],
    }),

    // PATCH update banner
    updateBanner: builder.mutation({
      query: ({ id, ...patch }) => ({
        url: `/admin/home-banners/${id}`,
        method: 'PUT',
        body: patch,
      }),
      invalidatesTags: ['Banner'],
    }),

    // DELETE banner
    deleteBanner: builder.mutation({
      query: (id) => ({
        url: `/admin/home-banners/${id}`,
        method: 'DELETE',
      }),
      invalidatesTags: ['Banner'],
    }),

  }),
});

// Export hooks generated by the API service
export const {
  useGetBannersQuery,
  useCreateBannerMutation,
  useUpdateBannerMutation,
  useDeleteBannerMutation,
} = homeBannerSlice;
