import { createApi, fetchBaseQuery } from "@reduxjs/toolkit/query/react";

// Define your base URL
const baseUrl = "https://back.biopluskw.com/api/v1";

// Create the API slice using RTK Query
export const pharmacyRequestsApi = createApi({
  reducerPath: "pharmacyRequestsApi",
  baseQuery: fetchBaseQuery({
    baseUrl,
    prepareHeaders: (headers) => {
      // Get the token from localStorage (or Redux state)
      const token = localStorage.getItem("token");

      // If a token exists, add it to the headers
      if (token) {
        headers.set("Authorization", `Bearer ${token}`);
      }

      return headers;
    },
  }),

  endpoints: (builder) => ({
    getPharmaciesRequests: builder.query({
      query: ({ page, limit }) => ({
        url: '/admin/product-offer/products/offers/requests',
        params: { page, limit }, // Pass page and limit as query parameters
      }),
    }),
   
    removeRequest: builder.mutation({
      query: (pharmacy) => ({
        url: "/admin/product-offer/products/offers/remove",
        method: "POST",
        body: pharmacy,
      }),
    }),
    processRequest: builder.mutation({
      query: (pharmacy) => ({
        url: "/admin/product-offer/products/offers/requests/process",
        method: "POST",
        body: pharmacy,
      }),
    }),
    
    
  }),
});

// Export hooks generated by the API service
export const {
 
  useGetPharmaciesRequestsQuery,
  useRemoveRequestMutation,
  useProcessRequestMutation
} = pharmacyRequestsApi;
