import { createApi, fetchBaseQuery } from "@reduxjs/toolkit/query/react";

// Define your base URL
const baseUrl = "https://back.biopluskw.com/api/v1";

// Create the API slice using RTK Query
export const pharmacyFiles = createApi({
  reducerPath: "pharmacyFiles",
  baseQuery: fetchBaseQuery({
    baseUrl,
    prepareHeaders: (headers) => {
      // Get the token from localStorage (or Redux state)
      // Get the token from localStorage (or Redux state)
      const token = localStorage.getItem("token");

      // If a token exists, add it to the headers
      if (token) {
        headers.set("Authorization", `Bearer ${token}`);
      }
      return headers;
    },
  }),

  endpoints: (builder) => ({
    getPharmacyFiles: builder.query({
      query: ({id, page, limit }) => ({
        url: `/admin/pharmacies/${id}/files`,
        params: { page, limit }, // Pass page and limit as query parameters
      }),
    }),
    addPharmacyFile: builder.mutation({
      query: ({id,data}) => ({
        url: `/admin/pharmacies/${id}/files`,
        method: "POST",
        body: data,
      }),
    }),
    updatePharmacyFile: builder.mutation({
      query: ({id, fileId, data}) => ({
        url: `/admin/pharmacies/${id}/files/${fileId}`,
        method: "PUT",
        body: data,
      }),
    }),
    deletePharmacyFile: builder.mutation({
      query: ({id, fileId}) => ({
        url: `/admin/pharmacies/${id}/files/${fileId}`,
        method: "DELETE",
      }),
    }),
  }),
});

// Export hooks generated by the API service
export const {
  useGetPharmacyFilesQuery,
  useAddPharmacyFileMutation,
  useUpdatePharmacyFileMutation,
  useDeletePharmacyFileMutation,
} = pharmacyFiles;
