import { createApi, fetchBaseQuery } from "@reduxjs/toolkit/query/react";

// Define your base URL
const baseUrl = "https://back.biopluskw.com/api/v1";

// Create the API slice using RTK Query
export const retrurnApi = createApi({
  reducerPath: "retrurnApi",
  baseQuery: fetchBaseQuery({
    baseUrl,
    prepareHeaders: (headers) => {
      // Get the token from localStorage (or Redux state)
      const token = localStorage.getItem("token");

      // If a token exists, add it to the headers
      if (token) {
        headers.set("Authorization", `Bearer ${token}`);
      }

      return headers;
    },
  }),

  endpoints: (builder) => ({
    getReturns: builder.query({
      query: ({ page, limit }) => ({
        url: '/admin/returns',
        params: { page, limit }, // Pass page and limit as query parameters
      }),
    }),
    getReturn: builder.query({
      query: (id) => `/admin/returns/${id}`,
    }),
    addReturn: builder.mutation({
      query: (data) => ({
        url: "/admin/returns",
        method: "POST",
        body: data,
      }),
    }),
    updateReturn: builder.mutation({
      query: ({ id, data }) => ({
        url: `/admin/returns/${id}`,
        method: "PUT",
        body: data,
      }),
    }),
    deleteReturn: builder.mutation({
      query: (id) => ({
        url: `/admin/returns/${id}`,
        method: "DELETE",
      }),
    }),
  }),
});

// Export hooks generated by the API service
export const {
  useGetReturnsQuery,
  useGetReturnQuery,
  useAddReturnMutation,
  useUpdateReturnMutation,
  useDeleteReturnMutation,
} = retrurnApi;
